init_control = {}        
init_control["high_depth"] = -20.0
init_control["low_depth"] = -70.0
init_control["frequency"] = 10
init_control["pid_depth"] = {}
init_control["pid_depth"]["kp"] = 0.1
init_control["pid_depth"]["ki"] = 0
init_control["pid_depth"]["kd"] = 0
init_control["pid_depth"]["integral_limit"] = 100.0
init_control["pid_depth"]["output_limit"] = 100.0
init_control["pid_v_vel"] = {}
init_control["pid_v_vel"]["kp"] = 1
init_control["pid_v_vel"]["ki"] = 0
init_control["pid_v_vel"]["kd"] = 0.1
init_control["pid_v_vel"]["integral_limit"] = 100.0
init_control["pid_v_vel"]["output_limit"] = 10.0        
init_control["pid_v_acc"] = {}
init_control["pid_v_acc"]["kp"] = 0.02
init_control["pid_v_acc"]["ki"] = 0.00005
init_control["pid_v_acc"]["kd"] = 0.8
init_control["pid_v_acc"]["integral_limit"] = 100.0
init_control["pid_v_acc"]["output_limit"] = 0.010035
init_pos = {}
init_pos["x"] = 0.0
init_pos["y"] = 0.0
init_pos["z"] = 0.0
init_vel = {}
init_vel["x"] = 0.0
init_vel["y"] = 0.0
init_vel["z"] = 0.0
init_acc = {}
init_acc["x"] = 0.0
init_acc["y"] = 0.0
init_acc["z"] = 0.0
init_buoyancy_engine = {}
init_buoyancy_engine["tank_volume"] = 0.002275
init_buoyancy_engine["initial_proportion_full"] = 1.0
# init_buoyancy_engine["initial_pump_rate"] = 0.0
# init_buoyancy_engine["max_pump_rate"] = rpm_to_q(self.max_rpm, init_buoyancy_engine["tank_volume"])
# init_buoyancy_engine["position"] = {}       
# init_buoyancy_engine["position"]["x"] = 0.5
# init_buoyancy_engine["position"]["y"] = 0.0
# init_buoyancy_engine["position"]["z"] = 0.05
init_motor = {}
init_motor["min_rpm"] = 1000
init_motor["max_rpm"] = 4000